# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.Owner'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='type',
            field=models.CharField(blank=True, choices=[('bedsitter', 'Bedsitter'), ('single', 'Single')], max_length=100, null=True),
        ),
    ]
