# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_auto_20170618_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
